name: Semgrep Scan

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep:
    name: Semgrep Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: python3 -m pip install semgrep

      - name: Run Semgrep
        run: semgrep scan --config auto --verbose --json --recursive > semgrep-results.json

      - name: Upload JSON Output
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-json
          path: semgrep-results.json
